In [85]:
# Importamos pandas

import pandas as pd
import numpy as np

# Configuramos los DataFrames de tal forma que muestren todas las columnas

pd.set_option("display.max_columns", None)

In [86]:
# Cargamos el archivo csv de Netflix y almacenamos los datos en un DataFrame

df_netflix = pd.read_csv("C:/xampp/htdocs/Master/data/netflix_titles.csv", index_col='show_id')

df_netflix.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [87]:
# Cargamos el archivo csv de Disney+ y almacenamos los datos en un DataFrame

df_disney = pd.read_csv("C:/xampp/htdocs/Master/data/disney_plus_titles.csv", index_col='show_id')

df_disney.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [88]:
# Unimos ambos df mediante concat

df_total = pd.concat([df_netflix, df_disney])

In [89]:
# Head Netflix

df_netflix.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [90]:
# Head Disney+

df_disney.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [91]:
# Tail Netflix

df_netflix.tail()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [92]:
# Tail Disney+

df_disney.tail()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

In [93]:
# Sample Netflix

df_netflix.sample(3)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s300,Movie,The Swarm,Just Philippot,"Suliane Brahim, Sofian Khammes, Marie Narbonne...",France,"August 6, 2021",2021,TV-14,102 min,"Horror Movies, Independent Movies, Internation...",A single mother breeds locusts as high-protein...
s4773,TV Show,Meteor Garden,NaN,"Shen Yue, Dylan Wang, Darren Chen, Connor Lian...",China,"July 14, 2018",2018,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Dong Shancai is determined to excel at her dre...
s8448,Movie,The Pass,Ben A. Williams,"Russell Tovey, Arinzé Kene, Lisa McGrillis, Ni...",United Kingdom,"January 1, 2019",2016,NR,87 min,"Dramas, Independent Movies, LGBTQ Movies",The lives and careers of two professional socc...

In [94]:
# Sample Disney+

df_disney.sample(3)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s321,Movie,700 Sharks,Luc Marescot,Paul Bandey,France,"January 1, 2021",2018,TV-PG,45 min,"Animals & Nature, Documentary",Follow an international team of scientists in ...
s941,Movie,High School Musical,Kenny Ortega,"Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lu...",United States,"November 12, 2019",2006,TV-G,100 min,"Coming of Age, Musical, Romance",A basketball star and a brainy girl find a pla...
s1358,Movie,The Wizards Return: Alex vs. Alex,Victor Gonzalez,"Selena Gomez, Jake T. Austin, Jennifer Stone, ...",United States,"November 12, 2019",2013,TV-G,59 min,"Comedy, Coming of Age, Fantasy",Alex creates a good and evil version of herself.

In [95]:
# Shape Netflix

df_netflix.shape

(8807, 11)

In [96]:
# Shape Disney+

df_disney.shape

(1450, 11)

In [97]:
# Size Netflix

df_netflix.size

96877

In [98]:
# Size Disney+

df_disney.size

15950

In [99]:
# Columns total

df_total.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [100]:
# Info total

df_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10257 entries, s1 to s1450
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          10257 non-null  object
 1   title         10257 non-null  object
 2   director      7150 non-null   object
 3   cast          9242 non-null   object
 4   country       9207 non-null   object
 5   date_added    10244 non-null  object
 6   release_year  10257 non-null  int64
 7   rating        10250 non-null  object
 8   duration      10254 non-null  object
 9   listed_in     10257 non-null  object
 10  description   10257 non-null  object
dtypes: int64(1), object(10)
memory usage: 961.6+ KB

In [101]:
# Dtypes total

df_total.dtypes

type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [102]:
# Isnull total

df_total.isnull().sum()

type               0
title              0
director        3107
cast            1015
country         1050
date_added        13
release_year       0
rating             7
duration           3
listed_in          0
description        0
dtype: int64

In [103]:
# Isna total

df_total.isna().sum()

type               0
title              0
director        3107
cast            1015
country         1050
date_added        13
release_year       0
rating             7
duration           3
listed_in          0
description        0
dtype: int64

In [104]:
# Duplicated total

df_total.duplicated().sum()

np.int64(0)

In [105]:
# Describe total

df_total.describe().T

,count,mean,std,min,25%,50%,75%,max
release_year,10257.0,2012.612655,12.21573,1925.0,2012.0,2017.0,2019.0,2021.0

In [106]:
# Vamos a seleccionar únicamente las películas

condicion_pelicula = df_total["type"]=="Movie"

df_total_pelicula = df_total[condicion_pelicula]

df_total_pelicula.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

In [107]:
# Creamos una condición donde solo obtengamos las series y películas que se hayan estrenado después de 2020

condicion_2020 = df_total["release_year"]>2020

df_total_2020 = df_total[condicion_2020]

df_total_2020.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

In [108]:
# Combinamos ambas condiciones para que se cumplan las dos

df_total_pelicula_2020 = df_total[condicion_pelicula & condicion_2020]

df_total_pelicula_2020.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...

In [109]:
# Si queremos que se cumpla al menos una de las dos condiciones

df_total_pelicula_o_2020 = df_total[condicion_pelicula | condicion_2020]

df_total_pelicula_o_2020.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [110]:
# Isin
# Para este filtro solo nos interesarán las películas y series producidas en UK y España

filtro_pais = ["United Kingdom", "Spain"]
uk_spain = df_total[df_total["country"].isin(filtro_pais)]
uk_spain.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
s66,TV Show,Numberblocks,NaN,"Beth Chalmers, David Holt, Marcel McCalla, Ter...",United Kingdom,"September 15, 2021",2021,TV-Y,6 Seasons,Kids' TV,"In a place called Numberland, math adds up to ..."
s73,TV Show,Jack Whitehall: Travels with My Father,NaN,"Jack Whitehall, Michael Whitehall",United Kingdom,"September 14, 2021",2021,TV-MA,5 Seasons,"British TV Shows, Docuseries, International TV...",Jovial comic Jack Whitehall invites his stuffy...
s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...

In [111]:
# Between
# Para este filtro solo nos interesarán las películas y series que han sido estrenadas entre 2005 y 2010

estreno_2005_2010 = df_total[df_total["release_year"].between(2005,2010, inclusive="both")]
estreno_2005_2010.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
s58,Movie,Naruto Shippûden the Movie: Bonds,Hajime Kamegaki,"Junko Takeuchi, Chie Nakamura, Noriaki Sugiyam...",Japan,"September 15, 2021",2008,TV-PG,93 min,"Action & Adventure, Anime Features, Internatio...",When strange ninjas ambush the village of Kono...
s59,Movie,Naruto Shippûden the Movie: The Will of Fire,Masahiko Murata,"Junko Takeuchi, Chie Nakamura, Kazuhiko Inoue,...",Japan,"September 15, 2021",2009,TV-PG,96 min,"Action & Adventure, Anime Features, Internatio...",When four out of five ninja villages are destr...
s60,Movie,Naruto Shippuden: The Movie,Hajime Kamegaki,"Junko Takeuchi, Chie Nakamura, Yoichi Masukawa...",Japan,"September 15, 2021",2007,TV-PG,95 min,"Action & Adventure, Anime Features, Internatio...",The adventures of adolescent ninja Naruto Uzum...
s61,Movie,Naruto Shippuden: The Movie: The Lost Tower,Masahiko Murata,"Junko Takeuchi, Chie Nakamura, Satoshi Hino, R...",Japan,"September 15, 2021",2010,TV-14,85 min,"Action & Adventure, Anime Features, Internatio...","When Naruto is sent to recover a missing nin, ..."

In [112]:
# Str.contains
# Buscamos las películas y series en las que ha aparecido Jennifer Lawrence

df_total_jennifer = df_total[df_total["cast"].str.contains("Jennifer Lawrence", case=False, na=False)]
df_total_jennifer.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s252,Movie,Like Crazy,Drake Doremus,"Anton Yelchin, Felicity Jones, Jennifer Lawren...",United States,"August 19, 2021",2011,PG-13,91 min,"Dramas, Independent Movies, Romantic Movies",A spirited exchange student and an American ma...
s703,Movie,Silver Linings Playbook,David O. Russell,"Bradley Cooper, Jennifer Lawrence, Robert De N...",United States,"June 17, 2021",2012,R,122 min,"Comedies, Dramas, Independent Movies",A man with bipolar disorder moves home with hi...
s7010,Movie,House at the End of the Street,Mark Tonderai,"Gil Bellows, Max Thieriot, Jennifer Lawrence, ...","United States, Canada","May 8, 2020",2012,PG-13,101 min,"Horror Movies, Thrillers",Moving to a new town proves even more stressfu...
s8751,Movie,Winter's Bone,Debra Granik,"Jennifer Lawrence, John Hawkes, Kevin Breznaha...",United States,"March 1, 2019",2010,R,100 min,"Dramas, Independent Movies","In this unflinching noir drama, a resilient te..."
s51,Movie,X-Men: First Class,Matthew Vaughn,"James McAvoy, Michael Fassbender, Rose Byrne, ...","United States, United Kingdom","November 5, 2021",2011,PG-13,132 min,"Action-Adventure, Science Fiction, Superhero","Following the classic mythology, X-Men: First ..."

In [113]:
# Filter
# Vamos a seleccionar las columnas de título y clasificación

df_total.filter(items=["title","rating"]).head()

                         title rating
show_id
s1        Dick Johnson Is Dead  PG-13
s2               Blood & Water  TV-MA
s3                   Ganglands  TV-MA
s4       Jailbirds New Orleans  TV-MA
s5                Kota Factory  TV-MA

In [114]:
# Eliminamos la fila 1448 de nuestro DataFrame, guardando el resultado en una variable

df_total_sin_1448 = df_total.drop("s1448", axis=0, inplace=False)

df_total_sin_1448.tail(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1445,Movie,Ice Age: Dawn Of The Dinosaurs,Carlos Saldanha,"Ray Romano, John Leguizamo, Denis Leary, Simon...","United States, United Kingdom, Australia","June 4, 2021",2009,PG,97 min,"Animation, Comedy, Family",Our prehistoric pals visit a world inhabited b...
s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

In [115]:
# Como se puede observar, el DataFrame original no se ve afectado

df_total.tail(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

In [116]:
# ¿Cuál es la media del año de estreno de series y películas para cada director?

año_media = df_total.groupby("director")["release_year"].mean()
año_media.head()

director
A. L. Vijay        2017.5
A. Raajdheep       2020.0
A. Salaam          1975.0
A.R. Murugadoss    2017.5
Aadish Keluskar    2018.0
Name: release_year, dtype: float64

In [117]:
# reset_index

año_media = año_media.reset_index()
año_media

                 director  release_year
0             A. L. Vijay        2017.5
1            A. Raajdheep        2020.0
2               A. Salaam        1975.0
3         A.R. Murugadoss        2017.5
4         Aadish Keluskar        2018.0
...                   ...           ...
5010     Ísold Uggadóttir        2018.0
5011  Óskar Thór Axelsson        2017.0
5012     Ömer Faruk Sorak        2007.5
5013         Şenol Sönmez        2017.0
5014            朱家欣 , 钟智行        2009.0

[5015 rows x 2 columns]

In [118]:
# Calcular la media, mediana, desviación, máximo y mínimo del año de estreno de las películas según la clasificación

estreno_clasificacion = df_total.groupby("rating")["release_year"].agg(["mean", "median", "std", "max", "min"]).reset_index()
estreno_clasificacion.tail()

      rating         mean  median        std   max   min
12     TV-PG  2012.403780  2017.0  13.717147  2021  1937
13      TV-Y  2016.473389  2018.0   5.180722  2021  1977
14     TV-Y7  2011.070968  2016.0  16.817649  2021  1928
15  TV-Y7-FV  2014.421053  2018.0  10.746140  2021  1985
16        UR  1999.333333  2008.0  22.300972  2016  1974

In [119]:
# groups

df_total.groupby("country").groups["South Korea"]

Index(['s105', 's125', 's290', 's457', 's546', 's557', 's687', 's732', 's763',
       's885',
       ...
       's8187', 's8258', 's8331', 's8380', 's8419', 's8464', 's8468', 's8576',
       's8614', 's8685'],
      dtype='object', name='show_id', length=199)

In [120]:
# get_group

df_total.groupby("country").get_group("South Korea").head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s105,TV Show,Tayo the Little Bus,NaN,"Robyn Slade, Kami Desilets",South Korea,"September 6, 2021",2016,TV-Y,2 Seasons,"Kids' TV, Korean TV Shows",As they learn their routes around the busy cit...
s125,TV Show,Pororo - The Little Penguin,NaN,NaN,South Korea,"September 2, 2021",2013,TV-Y7,3 Seasons,"Kids' TV, Korean TV Shows","On a tiny island, Pororo the penguin has fun a..."
s290,TV Show,The Crowned Clown,NaN,"Yeo Jin-goo, Lee Se-young, Kim Sang-kyung, Jun...",South Korea,"August 10, 2021",2019,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Standing in for an unhinged Joseon king, a loo..."
s457,TV Show,Her Private Life,NaN,"Park Min-young, Kim Jae-uk, Ahn Bo-hyun, Jung ...",South Korea,"July 15, 2021",2019,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...","An art curator's life unravels, as she tries t..."
s546,TV Show,YooHoo to the Rescue,NaN,"Kira Buckland, Ryan Bartley, Bryce Papenbrook,...",South Korea,"July 6, 2021",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows","In a series of magical missions, quick-witted ..."

In [121]:
# Vamos a crear una función que reciba el año de estreno y nos devuelva una etiqueta

def categorizar_estreno(año):
    """
    Función para categorizar años de estreno.

    Parámetros:
    - año (int): Número que se va a categorizar.

    Retorna:
    - str: Categoría a la que pertenece el año.
    """
    if año <= 1999:
        return 'Película antigua'
    elif 2000 <= año <= 2009:
        return 'Película de hace 20 años'
    elif 2010 <= año <= 2019:
        return 'Película de hace 10 años'
    else:
        return 'Película nueva'

In [122]:
# Ahora que tenemos la función creada vamos a aplicarla para nuestro DataFrame y para la columna del año de estreno
# Nota: Vamos a usar el total_2 para no realizar cambios importantes sobre el DataFrame original

df_total_2 = df_total
df_total_2["year category"] = df_total_2["release_year"].apply(categorizar_estreno)
df_total_2.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year category
show_id,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Película nueva
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Película nueva
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Película nueva
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Película nueva
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Película nueva

In [123]:
# Con apply también podemos cambiar el tipo de dato de la columna. Vamos a ver qué tipo de dato tiene la columna del año de estreno

df_total_2["release_year"].dtype

dtype('int64')

In [124]:
# Vamos a cambiarla a tipo float

# Definimos la función:

def cambiar_float(año):
    """
    Función para cambiar el tipo de un int a float.

    Parámetros:
    - año (int): Número que se va a convertir.

    Retorna:
    - float: El número proporcionado con el tipo cambiado a float.
    """
    return float(año)

In [125]:
# Llamamos a la función

df_total_2["release_year"] = df_total_2["release_year"].apply(cambiar_float)

In [126]:
# Comprobamos

df_total_2["release_year"].dtype

dtype('float64')

In [127]:
# lambda

# Vamos a hacer lo mismo para la columna de duración, volviéndola a pasar a int

df_total_2["release_year"] = df_total_2["release_year"].apply(lambda x: int(x))

In [128]:
# Comprobamos

df_total_2["release_year"].dtype

dtype('int64')

In [129]:
# Lambda con condicionales

df_total_2["type"] = df_total_2["type"].apply(lambda x: "Película" if x == "Movie" else "Serie")
df_total_2.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year category
show_id,,,,,,,,,,,,
s1,Película,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Película nueva
s2,Serie,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Película nueva
s3,Serie,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Película nueva
s4,Serie,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Película nueva
s5,Serie,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Película nueva

In [130]:
# Podemos usar una función lambda para utilizar funciones a las que le pasamos más de un parámetro

# Primero definiremos la función:

def serie_2015(col_serie, col_2015):
    """
    Función para identificar un usuario con unas características concretas.

    Parámetros:
    - col_serie (str): Columna que marca si el contenido es una serie
    - col_2015 (str): Columna que marca si el año de estreno es el 2015

    Retorna:
    - bool: Si las condiciones se cumplen o no
    """
    if col_serie == "TV Show" and col_2015 == "2015":
        return True
    else:
        return False

In [131]:
# Ahora llamamos a la función utilizando apply y lambda

df_total_2["serie 2015"] = df_total_2.apply(lambda x: serie_2015(x["type"], x["release_year"]), axis=1)
df_total_2.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year category,serie 2015
show_id,,,,,,,,,,,,,
s1,Película,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Película nueva,False
s2,Serie,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Película nueva,False
s3,Serie,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Película nueva,False
s4,Serie,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Película nueva,False
s5,Serie,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Película nueva,False

In [135]:
# pivot_table

df_total.pivot_table(values="release_year", index="type", columns="rating", aggfunc="count")

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Película,1.0,1.0,1.0,294.0,3.0,75.0,522.0,556.0,797.0,1464.0,359.0,2062.0,721.0,134.0,175.0,12.0,3.0
Serie,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,2.0,775.0,179.0,1145.0,443.0,223.0,290.0,7.0,NaN

In [136]:
# Melt

# Antes vamos a transformar el DataFrame para poder ver mejor el resultado del método melt

df_total_3 = df_total.head(3)
df_total_3

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year category,serie 2015
show_id,,,,,,,,,,,,,
s1,Película,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Película nueva,False
s2,Serie,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Película nueva,False
s3,Serie,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Película nueva,False

In [137]:
pd.melt(df_total_3, id_vars="type", value_vars=["release_year", "rating"], var_name="variable", value_name="valor")

       type      variable  valor
0  Película  release_year   2020
1     Serie  release_year   2021
2     Serie  release_year   2021
3  Película        rating  PG-13
4     Serie        rating  TV-MA
5     Serie        rating  TV-MA